exams/urls.py
from django.urls import path
from . import views

"""Defines URL patterns for exams"""
app_name = 'exams'
urlpatterns = [
    path('', views.index, name='index'),
    path('studentregistration/', views.student_registration, name='stud_reg'),
    path('teacherregistration/', views.teacher_registration, name="teacher_reg"),
    path('createterm/', views.term_creation, name='create_term'),
    path('studentprofile/<adm_no>/', views.student_profile_page, name='profiler'),
    path('teacherprofile/<t_id>/', views.teacher_profile_page, name="t_profile"),
    path('studentlist/', views.all_students, name='allstudents'),
    path('teacherlist/', views.all_teachers, name='allteachers'),
    path('classlist/<int:daro_id>/', views.student_class_list, name='class_list'),
    path('createexam/', views.create_exam, name='create_exam'),
    path('examlist/', views.exams_page, name='exams_list'),
]

school/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('exams/', include('exams.urls')),
    path('users/', include('users.urls')),
]

exams/models.py
from django.db import models


# Create your models here.


class Stream(models.Model):
    stream_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Darasa(models.Model):
    daro_id = models.AutoField(primary_key=True, default=None)
    daro_name = models.CharField(max_length=15)
    stream = models.ForeignKey(Stream, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.stream} {self.daro_name}'


class Student(models.Model):
    """Student information"""
    adm = models.IntegerField(unique=True, default=None)
    f_name = models.CharField(max_length=20)
    l_name = models.CharField(max_length=20)
    male = 'm'
    female = 'f'
    GENDER_CHOICES = [
        (male, 'MALE'),
        (female, 'FEMALE'),
    ]
    gender = models.CharField(choices=GENDER_CHOICES,max_length=1, null=False, default=None)
    birthday = models.DateField(null=True, blank=True)
    darasa = models.ForeignKey(Darasa, null=True, on_delete=models.SET_NULL)
    profile_pic = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f'{self.f_name} {self.l_name}'


class Teacher(models.Model):
    tch_id = models.AutoField(primary_key=True, default=None)
    f_name = models.CharField(max_length=15)
    l_name = models.CharField(max_length=15)
    tsc_no = models.IntegerField(default=None)
    telephone = models.IntegerField(null=True)
    email = models.EmailField(max_length=20, null=True)

    def __str__(self):
        return f'{self.f_name} {self.l_name}'


class Subject(models.Model):
    SUBJECT_CHOICES = [
        ('ENGLISH', 'ENGLISH'),
        ('KISWAHILI', 'KISWAHILI'),
        ('MATHEMATICS', 'MATHEMATICS'),
        ('BIOLOGY', 'BIOLOGY'),
        ('PHYSICS', 'PHYSICS'),
        ('CHEMISTRY', 'CHEMISTRY'),
        ('HISTORY', 'HISTORY'),
        ('GEOGRAPHY', 'GEOGRAPHY'),
        ('CRE', 'CRE'),
        ('BS', 'BUSINESS STUDIES'),
        ('AGRICULTURE','AGRICULTURE'),
    ]
    sub_name = models.CharField(choices=SUBJECT_CHOICES, max_length=15, null=False, blank=False)
    teacher = models.ForeignKey(Teacher, default=None, blank=False, null=True, on_delete=models.SET_DEFAULT)
    darasa = models.ForeignKey(Darasa, default=None, blank=True, null=True, on_delete=models.SET_DEFAULT)

    def __str__(self):
        return f'{self.darasa} {self.sub_name}'


class Staff(models.Model):
    staff_id = models.AutoField(primary_key=True, default=None)
    f_name = models.CharField(max_length=15)
    s_name = models.CharField(max_length=15)


class Department(models.Model):
    dpt_id = models.AutoField(primary_key=True, default=None)
    dpt_name = models.CharField(max_length=15)


class Term(models.Model):
    # term choices should come from existing term as below
    term_choices = [
        (None, 'Pick Term'),
        (1, 'One'),
        (2, 'Two'),
        (3, 'Three')
    ]
    name = models.IntegerField(choices=term_choices, null=False, default=None)
    start_date = models.DateField()
    closing_date = models.DateField()

    def __str__(self):
        return f'Term {self.name}'


class Examination(models.Model):
    name = models.CharField(max_length=55)
    start_date = models.DateField()
    end_date = models.DateField()

    # no need for the exam attribute below since a term cannot be deleted once done
    # can be determined by a function that determines whether  the start date of the exam is within the term dates

    def set_term(self):
        terms = Term.objects.all()
        for term in terms:
            if term.start_date < Examination.start_date < term.end_date:
                self.term = term


class ExamResult(models.Model):
    """ The exact score scored by a student in a subject in that particular exam """
    exam = models.ForeignKey(Examination, null=False, on_delete=models.CASCADE, default=None)
    student = models.ForeignKey(Student, null=False, on_delete=models.CASCADE, default=None)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, default=None)
    score = models.IntegerField(default=None)

exams/forms.py
from .models import Student, Teacher, Examination, Subject, Term, Darasa
from django import forms
from django.core.validators import RegexValidator


class CreateStudentForm(forms.ModelForm):
    adm = forms.IntegerField(
        label='Admission Number',
        help_text="As it appears on ID",
        # Strip: THe value will be stripped of leading and trailing whitespaces
        # strip=True,
        # validators=[RegexValidator(r'^[]*$', message="Only letters allowed!")],
        widget=forms.NumberInput(attrs={'placeholder': 'Admission No'})
    )

    f_name = forms.CharField(
        label='First Name', min_length=3, max_length=50,
        help_text="As it appears on ID",
        # Strip: THe value will be stripped of leading and trailing whitespaces
        # strip=True,
        # validators=[RegexValidator(r'^[]*$', message="Only letters allowed!")],
        widget=forms.TextInput(attrs={'placeholder': 'First Name'})
    )

    l_name = forms.CharField(
        label='Last Name', min_length=3, max_length=50,
        help_text="As it appears on ID",
        # Strip: THe value will be stripped of leading and trailing whitespaces
        # strip=True,
        # validators=[RegexValidator(r'^[]*$', message="Only letters allowed!")],
        widget=forms.TextInput(attrs={'placeholder': 'Last Name'})
    )

    gender = forms.ChoiceField(
        choices=Student.GENDER_CHOICES,
        label='Gender',
        help_text="As it appears on ID",
        # Strip: THe value will be stripped of leading and trailing whitespaces
        # strip=True,
        # validators=[RegexValidator(r'^[]*$', message="Only letters allowed!")],
        widget=forms.RadioSelect(attrs={'placeholder': 'Gender', 'class': 'form-control'})
    )

    birthday = forms.CharField(
        label='Date of birth',
        help_text="Enter birth date",
        # Strip: THe value will be stripped of leading and trailing whitespaces
        # strip=True,
        # validators=[RegexValidator(r'^[]*$', message="Only letters allowed!")],
        widget=forms.DateInput(attrs={'placeholder': 'Birth date', 'type': 'date'})
    )

    darasa = forms.ModelChoiceField(
        label='Class',
        queryset=Darasa.objects.all(),
        help_text="Enter class to be admitted",
        widget=forms.Select(attrs={'placeholder': 'Class admitted', 'class': 'form-control'})
    )

    class Meta:
        model = Student

        fields = '__all__'
        # fields = ['adm', 'f_name', 'l_name', 'gender', 'birthday', 'darasa']
        # labels = {'adm': 'Admission number', 'f_name': 'First Name', 'l_name': 'Last Name', 'gender': 'Gender',
        #          'birthday': 'Date of Birth', 'darasa': 'Class admitted'}
        # widgets = {
        #    'birthday': forms.DateInput(attrs={'type': 'date'})
        # }


class CreateTeacherForm(forms.ModelForm):
    f_name = forms.CharField(
        label='First Name', min_length=3, max_length=50,
        help_text="As it appears on ID",
        # Strip: THe value will be stripped of leading and trailing whitespaces
        strip=True,
        # validators=[RegexValidator(r'^[]*$', message="Only letters allowed!")],
        widget=forms.TextInput(attrs={'placeholder': 'First Name'})
    )

    l_name = forms.CharField(
        label='Last Name', min_length=3, max_length=50,
        help_text="As it appears on ID",
        # validators=[RegexValidator(r'^[a-zA-Z]*$', message="Only letters allowed!")],
        widget=forms.TextInput(attrs={'placeholder': 'Last Name'})
    )

    tsc_no = forms.CharField(
        label='TSC Number', min_length=6, max_length=10,
        # validators=[RegexValidator(r'^[a-zA-Z]*$', message="Only letters allowed!")],
        widget=forms.TextInput(attrs={'placeholder': 'TSC'})
    )

    email = forms.CharField(
        label='Email Address', min_length=3, max_length=50,
        # validators=[RegexValidator(r'^[a-zA-Z]*$', message="Only letters allowed!")],
        widget=forms.TextInput(attrs={'placeholder': 'name@example.com'})
    )

    telephone = forms.CharField(
        label='Phone Number', min_length=8, max_length=15,
        # validators=[RegexValidator(regex=r'^[0-9]*$', message="Only numbers allowed!")],
        widget=forms.TextInput(attrs={'placeholder': 'Phone'})
    )

    class Meta:
        model = Teacher

        fields = '__all__'
        # fields = ['f_name', 'l_name', 'tsc_no', 'telephone', 'email']


class NewTerm(forms.ModelForm):
    name = forms.ChoiceField(
        choices=Term.term_choices,
        label='Enter Term',
        # validators=[RegexValidator(r'^[a-zA-Z]*$', message="Only letters allowed!")],
        widget=forms.Select(attrs={'placeholder': 'eg, Term One', 'class': 'form-control'})
    )

    start_date = forms.DateField(
        label='Start Date',
        # validators=[RegexValidator(r'^[a-zA-Z]*$', message="Only letters allowed!")],
        widget=forms.DateInput(attrs={'placeholder': 'Start', 'type': 'date'})
    )

    closing_date = forms.DateField(
        label='Closing Date',
        # validators=[RegexValidator(regex=r'^[0-9]*$', message="Only numbers allowed!")],
        widget=forms.DateInput(attrs={'placeholder': 'Closing', 'type': 'date'})
    )

    class Meta:
        model = Term

        fields = '__all__'
        #  fields = ['name','start_date','closing_date']


class NewExam(forms.ModelForm):
    name = forms.CharField(
        label='Exam Name',
        # validators=[RegexValidator(r'^[a-zA-Z]*$', message="Only letters allowed!")],
        widget=forms.TextInput(attrs={'placeholder': 'eg, Opener', 'class': 'form-control'})
    )

    start_date = forms.DateField(
        label='Start Date',
        # validators=[RegexValidator(r'^[a-zA-Z]*$', message="Only letters allowed!")],
        widget=forms.DateInput(attrs={'placeholder': 'Start', 'type': 'date'})
    )

    closing_date = forms.DateField(
        label='Closing Date',
        # validators=[RegexValidator(regex=r'^[0-9]*$', message="Only numbers allowed!")],
        widget=forms.DateInput(attrs={'placeholder': 'Closing', 'type': 'date'})
    )

    class Meta:
        model = Examination

        fields = '__all__'
        #  fields = ['name','start_date','closing_date']

exams/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
# from django.http import HttpResponseRedirect
from .forms import CreateStudentForm, CreateTeacherForm, NewTerm, NewExam
from .models import Subject, Student, Teacher, Stream, Darasa, Examination


# Create your views here.


def index(request):
    return render(request, 'exams/index.html')


def student_registration(request):
    if request.method != 'POST':
        form = CreateStudentForm()
    else:
        form = CreateStudentForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "Reqistered successfully")
            return redirect('exams:index')

    context = {'form': form}
    return render(request, 'exams/student_registration.html', context)


def teacher_registration(request):
    if request.method != 'POST':
        form = CreateTeacherForm()
    else:
        form = CreateTeacherForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Reqistered successfully nice!")
            return redirect('exams:index')
    context = {'form': form}
    return render(request, 'exams/teacher_registration.html', context)


def term_creation(request):
    if request.method != 'POST':
        form = NewTerm()
    else:
        form = NewTerm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Reqistered successfully nice!")
            return redirect('exams:index')
    context = {'form': form}
    return render(request, 'exams/new_term.html', context)


def student_profile_page(request, adm_no):
    student = Student.objects.get(adm=adm_no)
    context = {'student': student}
    return render(request, "exams/student_profile.html", context)


def teacher_profile_page(request, t_id):
    teacher = Teacher.objects.get(tch_id=t_id)
    context = {'teacher': teacher}
    return render(request, "exams/teacher_profile.html", context)


def all_students(request):
    streams = Stream.objects.all()
    darasas = Darasa.objects.all()
    context = {'streams': streams, 'darasas': darasas}
    return render(request, 'exams/students.html', context)


def all_teachers(request):
    teachers = Teacher.objects.all()
    context = {'teachers': teachers}
    return render(request, 'exams/teachers.html', context)


def student_class_list(request, daro_id):
    darasa = Darasa.objects.get(pk=daro_id)
    students = Student.objects.all().filter(darasa=darasa)
    context = {'darasa': darasa, 'students': students}
    return render(request, 'exams/daro_list.html', context)


def create_exam(request):
    if request.method != 'POST':
        form = NewExam()
    else:
        form = NewExam(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Reqistered successfully nice!")
            return redirect('exams:index')
    context = {'form': form}
    return render(request, 'exams/create_exam.html', context)


def exams_page(request):
    exams = Examination.objects.all()
    context = {'exams': exams}
    return render(request, 'exams/exams_page.html', context)

exams/templates/exams/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'exams/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'exams/css/style.css' %}" type="text/css">
    </head>
    <body style="background-color: #FCEFEF;">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid" style="background-color: #BEE4D7;">
                <a class="navbar-brand" href="{% url 'exams:index' %}">
                    <img src="{% static 'exams/images/logo.png' %}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
                    Cheptoroi Secondary School
                </a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'exams:exams_list' %}">Exams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'exams:allstudents' %}">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'exams:allteachers' %}">Teachers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="offcanvas offcanvas-start" tabindex="-1" id="sidebar">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title">Sidebar</h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
            <!-- Sidebar content goes here -->
                <a class="btn btn-custom hover-effect-two" href="{% url 'exams:allstudents' %}">Students</a>

            </div>
        </div>

        <button class="btn btn-custom-sidebar hover-effect-two" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebar" style="position:fixed; margin-top:230px; width:7%; font-size:14px;">
          Sidebar
        </button>
        <script src="{% static 'exams/js/bootstrap.bundle.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>
{% block content %} {% endblock content%}

exams/templates/exams/create_exam.html
{% extends "exams/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<head>
    <title></title>
</head>
<body>
    <div class="form-group">
        <form method="post" action="{% url 'exams:create_exam' %}" class="card p-3 mt-3 bg-one" autocomplete="off">
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    {{form.name|as_crispy_field}}
                </div>
                <div class="col-6">
                    {{form.start_date|as_crispy_field}}
                    {{form.closing_date|as_crispy_field}}
                </div>
            </div>
            <button type="submit" class="btn btn-outline-primary mt-3" style="width:90px;">Submit</button>
        </form>

        <!--Message from backend-->
        {% for message in messages %}
            {% if message.tags == "success" %}
                <div class=" text-center alert alert-primary alert-dismissible fade show" role="alert">{{message}}
                    <a href="{% url 'exams:exams_list' %}" type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</body>
{% endblock content %}

exams/templates/exams/daro_list.html
{% extends 'exams/base.html' %}

{% block content %}



<head>
    <title></title>
    {% load static %}
    <!--<link rel="stylesheet" href="{% static 'exams/tables.css' %}" type="text/css">-->
</head>

<body>
    <div class="container">
        <h5 class="text-center">Class {{darasa.daro_name}}</h5>
        <table class="table">
            <thead>
                <tr>
                    <th>Admission Number</th>
                    <th>Full Name</th>
                    <th>Gender</th>
                    <th>Date of Birth</th>
                </tr>
            </thead>

            <tbody>
                {% for student in students %}
                <tr>
                    <td>{{ student.adm }}</td>
                    <td><a href="{% url 'exams:profiler' student.adm %}" style="text-decoration:none; color:black;">{{ student.f_name }} {{ student.l_name }}</a></td>
                    <td>{{ student.gender }}</td>
                    <td>{{ student.birthday }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!--
    <h2>Class {{darasa.daro_name}}</h2>
    <div class="table">
        <table>
            <tr>
                <th>Admission Number</th>
                <th>Full Name</th>
                <th>Gender</th>
                <th>Date of Birth</th>
                <th>Class</th>
            </tr>
            {% for student in students %}
            <tr>
                <td>{{ student.adm }}</td>
                <td><a href="{% url 'exams:profiler' student.adm %}">{{ student.f_name }} {{ student.l_name }}</a></td>
                <td>{{ student.gender }}</td>
                <td>{{ student.birthday }}</td>
                <td>{{ student.darasa }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>-->
</body>

{% endblock content %}

exams/templates/exams/new_term.html
{% extends 'exams/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<head>
    <title></title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'exams/forms.css' %}" type="text/css">
</head>
<body>
    <h3 class="text-center">Term Initialization</h3>
    <div class="form-group">
        <form action="{% url 'exams:teacher_reg' %}" method="post" class="card p-2 mt-3" autocomplete="off" novalidate>
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    {{form.name|as_crispy_field}}
                </div>
                <div class="col-6">
                    {{form.start_date|as_crispy_field}}
                    {{form.closing_date|as_crispy_field}}
                </div>
            </div>
            <button type="submit" class="btn btn-outline-primary mt-3" style="width:90px;">Submit</button>
        </form>
        <!--Message from backend-->
        {% for message in messages %}
            {% if message.tags == "success" %}
                <div class=" text-center alert alert-primary alert-dismissible fade show" role="alert">{{message}}
                    <a href="{% url 'exam:allstudents' %}" type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</body>

{% endblock content %}

exams/templates/exams/student_registration.html
{% extends "exams/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<head>
    <title></title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'exams/forms.css' %}" type="text/css">
</head>
<body>
    <div class="form-group">
        <form method="post" action="{% url 'exams:stud_reg' %}" class="card p-3 mt-3" autocomplete="off">
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    {{form.f_name|as_crispy_field}}
                    {{form.l_name|as_crispy_field}}

                </div>
                <div class="col-6">
                    {{form.adm|as_crispy_field}}
                    {{form.gender|as_crispy_field}}
                </div>
            </div>
            <div class="row">
                <div class="col-2">
                    {{form.birthday|as_crispy_field}}
                </div>
                <div class="col-5">
                    {{form.darasa|as_crispy_field}}
                </div>
                <!--<div class="col-5">
                    {{form.profile_pic|as_crispy_field}}
                </div>-->
            </div>
            <button type="submit" class="btn btn-outline-primary mt-3" style="width:90px;">Submit</button>
        </form>

        <!--Message from backend-->
        {% for message in messages %}
            {% if message.tags == "success" %}
                <div class=" text-center alert alert-primary alert-dismissible fade show" role="alert">{{message}}
                    <a href="{% url 'exams:allstudents' %}" type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</body>
{% endblock content %}

exams/templates/exams/students.html
{% extends 'exams/base.html' %}


{% block content %}

<div class="container">
    {% for stream in streams %}
    <button class="btn btn-outline-secondary hover-effect-two dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        FORM {{stream}}
    </button>
    <div class="dropdown" style="margin-bottom:10px;">

        <ul class="dropdown-menu bg-one">
        {% for darasa in darasas %}
            {% if darasa.stream == stream %}
                <li>
                    <a class="dropdown-item" href="{% url 'exams:class_list' darasa.daro_id %}">{{darasa.daro_name}}</a>
                </li>
            {% endif %}
        {% endfor %}
        </ul>

    </div>
    {% endfor %}


    <a class="btn btn-custom hover-effect" href="{% url 'exams:stud_reg' %}">Add Student</a>

</div>
{% endblock content %}

exams/templates/exams/teacher_registration.html
{% extends 'exams/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<head>
    <title></title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'exams/forms.css' %}" type="text/css">
</head>
<body>
    <h3 class="text-center">Teacher registration</h3>
    <div class="form-group">
        <form action="{% url 'exams:teacher_reg' %}" method="post" class="card p-2 mt-3" autocomplete="off" novalidate>
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    {{form.f_name|as_crispy_field}}
                </div>
                <div class="col-6">
                    {{form.l_name|as_crispy_field}}
                </div>
            </div>
            <hr style="border: 1px solid #007bff;">
            <div class="row">
                <div class="col-4">
                    {{form.tsc_no|as_crispy_field}}
                    {{form.telephone|as_crispy_field}}
                    {{form.email|as_crispy_field}}
                </div>
            </div>
            <hr style="border: 1px solid #007bff;">
            <button type="submit" class="btn btn-outline-primary mt-3" style="width:90px;">Submit</button>
        </form>
        <!--Message from backend-->
        {% for message in messages %}
            {% if message.tags == "success" %}
                <div class=" text-center alert alert-primary alert-dismissible fade show" role="alert">{{message}}
                    <a href="{% url 'exams:allstudents' %}" type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</body>

{% endblock content %}

exams/templates/exams/teachers.html
{% extends 'exams/base.html' %}
{% load static %}


{% block content %}


<body>
    <!--<div class="container">
        <h5 class="text-center">Teachers</h5>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>TSC</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <!-- <th>Subjects</th>
                </tr>
            </thead>

            <tbody>
                {% for teacher in teachers %}
                <tr>
                    <td>
                        <a href="{% url 'exams:t_profile' teacher.tch_id %}" style="text-decoration:none; color:black;">
                            {{ teacher.f_name }} {{ teacher.l_name }}
                        </a>
                    </td>
                    <td>{{ teacher.tsc_no }}</td>
                    <td>{{ teacher.telephone }}</td>
                    <td>{{ teacher.email }}</td>
                    <!-- <td>{{ teacher.subjects }}</td>
                </tr>
                {% empty %}
                <tr>No teachers registered yet</tr>
                {% endfor %}
            </tbody>

        </table>
        <a class="btn btn-custom hover-effect" href="{% url 'exams:teacher_reg' %}">Add Teacher</a>
    </div>-->

    <div class="container">

        <div class="row">

            <div class="col-md-12">
                <h2 class="text-white text-center">
                    Meet our team members
                </h2>
            </div>
            {% for teacher in teachers %}
            <div class="col-lg-3 col-md-4 col-sm-3">
                <div class="shadow d-flex flex-column justify-content-center align-items-center p-3 bg-three rounded-lg">
                    <div class="person-img">
                        <img src="{% static 'exams/images/showcase.avif' %}" alt="" class="img-fluid rounded-circle">
                    </div>
                    <div class="person-name my-2">
                            <h3 class="text-white">{{ teacher.f_name }} {{ teacher.l_name }}</h3>
                    </div>
                    <div class="info">
                        <h6 class="text-white">English Teacher</h6>
                    </div>
                    <div class="social-icons">
                        <a href="#" class="text-white">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="text-white">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="text-white">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                    </div>
                    <button class="btn btn-custom hover-effect btn-lg btn-block">
                        <a href="{% url 'exams:t_profile' teacher.tch_id %}" style="text-decoration:none; color:black;">
                            View Profile
                        </a>
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>

        <a class="btn btn-custom hover-effect mt-3" href="{% url 'exams:teacher_reg' %}">Add Teacher</a>
    </div>
</body>



{% endblock content %}